### ISSUE TITLE
Port Gradle build configuration to Windows

### ISSUE THREAD

**Issue by liblit** [liblit/WALA#2]
The `build.gradle` scripts are mostly platform-independent, but not entirely. To build and test WALA on Windows, we at least need to fill in the path to the Java dynamic library:

https://github.com/liblit/WALA/blob/4374ead1db1127bf8a13403b4354efeb1508bef6/com.ibm.wala.cast/build.gradle#L48-L50

Other fixes might be needed too; we won’t know until we try it and see what breaks.

That being said, is WALA itself even supported on Windows? If not, then this whole issue is moot and may as well be relabeled `wontfix`.

**Comment by msridhar** [comment]
Windows is not actively supported, so this can be low priority

**Comment by liblit** [comment]
In theory, Windows build support should be backed up by automated regression testing to ensure that Windows builds *keep* working. Unfortunately, [Travis-CI is currently not an option for that](https://github.com/travis-ci/travis-ci/issues/2104). Maybe someday that will change, or perhaps there are other Travis-like systems that we could use.
