### ISSUE TITLE
Port Gradle build configuration to macOS

### ISSUE THREAD

**Issue by liblit** [liblit/WALA#3]
The `build.gradle` scripts are mostly platform-independent, but not entirely. To build and test WALA on MacOS, we at least need to fill in the path to the Java dynamic library:

https://github.com/liblit/WALA/blob/4374ead1db1127bf8a13403b4354efeb1508bef6/com.ibm.wala.cast/build.gradle#L44-L46

Other fixes might be needed too; we won’t know until we try it and see what breaks.

That being said, is WALA itself even supported on MacOS? If not, then this whole issue is moot and may as well be relabeled `wontfix`.

**Comment by msridhar** [comment]
WALA is most definitely supported on Mac 😄 That's how I use it the most.  So we'll need to fix this one.  Probably we should enable running WALA regression on Macs on Travis as well at some point.

**Comment by SunghoLee** [comment]
I made a new pull request that fills the shared library path for OSX.

**Comment by liblit** [comment]
Excellent. Thank you, @SunghoLee.

Do MacOS Gradle builds now work just as well as Linux Gradle builds? Specifically, does `./gradlew assemble testClasses javadoc` succeed on MacOS? We already know that [full regression testing does not yet work](https://github.com/liblit/WALA/issues/5) even on Linux, but these other tasks should be doing OK. Note that you may see [some Javadoc warnings](https://github.com/liblit/WALA/issues/4), but should not see any errors.

Or is your shared library path contribution just one step, with more MacOS work still needed? Either way, I do plan to accept [your pull request](https://github.com/liblit/WALA/pull/8). I just need to know whether I should close this issue at the same time, or leave it open for further work.

**Comment by SunghoLee** [comment]
Oops, there is an error in `./gradlew assmble` with the path. The error message is like below:
`clang: error: no such file or directory: '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/amd64/server'`
I think that this error is not due to the OSX path because `/jre/lib/amd64/server` is a linux path. But it is good to postpone acceptance of the pull request until fixing it. I will try to revise `build.gradle` and comment again when I succeed in `./gradlew assemble testClasses javadoc`.

**Comment by liblit** [comment]
Once have working MacOS builds, it would be great to include that in Travis-CI automated testing to ensure that MacOS *keeps* working. More info:

- [Testing Your Project on Multiple Operating Systems](https://docs.travis-ci.com/user/multi-os/)
- [The OS X Build Environment](https://docs.travis-ci.com/user/reference/osx/)

**Comment by SunghoLee** [comment]
@liblit, sorry for my late response. I checked that `./gradlew assemble testClasses javadoc` work fine in OSX. The previous problem is just due to my gradle version. The pull request works fine.

In the `.travis.yml`, I could not find anything to do regarding to OS. Can I just add 
```
os:
  - linux
  - osx
```
to the file?

**Comment by liblit** [comment]
> I checked that `./gradlew assemble testClasses javadoc` work fine in OSX. The previous problem is just due to my gradle version.

Excellent!

> The pull request works fine.

OK, in that case I will go ahead and update [your pull request](https://github.com/liblit/WALA/pull/8) with respect to recent changes on the `gradle-and-buildship` branch, since that request is currently a bit outdated. If the updated request still passes the Linux tests on Travis CI, then I will accept and merge it. I still want us to add Travis CI testing using OS X, but that can be the next step. I will leave *this* issue open until we have Travis CI working, though.

> In the `.travis.yml`, I could not find anything to do regarding to OS. Can I just add [...] to the file?

Beats me. Try it and see what happens. If it breaks, try to fix it. The links I gave [above](#issuecomment-358745074) should help, but I have never worked with Travis CI and OS X before.

**Comment by liblit** [comment]
As of 6d4760c40b040a8805bb73bb073b31ee60343a5e, I have merged in a large collection of build fixes for macOS + Gradle. Along with those fixes I have also enabled [macOS testing using Travis CI](https://travis-ci.org/liblit/WALA/jobs/339579100). I had to exclude a single test on macOS only:

https://github.com/liblit/WALA/blob/6d4760c40b040a8805bb73bb073b31ee60343a5e/com.ibm.wala.cast.test/build.gradle#L103-L105

This is the test that involves loading native code, so I am not surprised that it needs further work. Getting that to work in the Linux + Gradle build was a challenge as well.

Unfortunately I do not have a personal macOS box, so this will be hard for me to work on. @SunghoLee, perhaps you can give it a try? I think that if you can get this one test working, then the macOS +Gradle build will be caught up to the same point as the Linux + Gradle build.

**Comment by SunghoLee** [comment]
@liblit, Okay, I will try to do that. However, I don't know exactly what the test does. Could you give me some examples that I can check whether the test works correctly or not?

**Comment by liblit** [comment]
@SunghoLee, I have only limited knowledge of what this test does myself. I know that it runs the `testNativeCAst` method in the `com.ibm.wala.cast.test.TestNativeTranslator` class. I know that code within that class loads a native `xlator_test` shared library that Gradle should already have built when the test is run. This shared library contains the C code found in `com.ibm.wala.cast.test/harness-src/c/smoke.cpp`, which implements the native `inventAst` method found in the `com.ibm.wala.cast.test.TestNativeTranslator` class. So probably something is going wrong with that process of finding and loading the native shared library.

If you look in `com.ibm.wala.cast.test/build.gradle`, you should see a `xlator_test(NativeLibrarySpec) { ... }` block that tells Gradle how to build the shared library. On Linux, that needs some extra `-Wl,-rpath` flags at link time to help the `xlator_test` shared library find other shared libraries that it will need. Maybe macOS needs something similar? I don’t know.

When running tests, the `--tests` Gradle flag may be useful to focus just on this one test instead of running everything:

```
% cd com.ibm.wala.cast.test
% ../gradlew test --tests com.ibm.wala.cast.test.TestNativeTranslator
```

The `--info` flag might also be useful to get a more verbose picture of what Gradle is trying to do when running this test. For example, when I use that flag on Linux, I can see the exact `java` command line used for the test with all of its arguments. That makes it easy for me to rerun this test by hand, tweak arguments, see if something is missing from the command line, look for diagnostic messages on `stdout` or `stderr`, etc. Presumably macOS is similar.
